"""add costs before to inventory movements

Revision ID: 1a48d631b91f
Revises: 3c7c8fec033a
Create Date: 2026-09-29 12:11:57.786132

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a48d631b91f"
down_revision: str | Sequence[str] | None = "3c7c8fec033a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_movements",
        sa.Column("average_cost_before", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "inventory_movements",
        sa.Column("last_cost_before", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    # ### end Alembic commands ###
    # Autogenerate does not detect CHECK constraints. Existing rows stay NULL: the previous
    # last cost cannot be derived from history, so their reversals use the inverse formula.
    op.create_check_constraint(
        op.f("ck_inventory_movements_costs_before_non_negative"),
        "inventory_movements",
        "average_cost_before >= 0 AND last_cost_before >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("ck_inventory_movements_costs_before_non_negative"),
        "inventory_movements",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_movements", "last_cost_before")
    op.drop_column("inventory_movements", "average_cost_before")
    # ### end Alembic commands ###
