"""create customers

Revision ID: 16dc3234dce6
Revises: 1a48d631b91f
Create Date: 2026-09-29 13:08:28.852764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    ("customers.read", "Consultar clientes."),
    ("customers.manage", "Crear, editar y desactivar clientes."),
]
ROLES = ["admin", "cashier"]
# 222222222222 is the document DIAN uses for "consumidor final".
DEFAULT_CUSTOMER = {
    "document_type": "cc",
    "document_number": "222222222222",
    "name": "Consumidor final",
}

# revision identifiers, used by Alembic.
revision: str = "16dc3234dce6"
down_revision: str | Sequence[str] | None = "1a48d631b91f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=10), nullable=False),
        sa.Column("document_number", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type IN ('nit', 'cc', 'ce', 'passport', 'other')",
            name=op.f("ck_customers_document_type_valid"),
        ),
        sa.CheckConstraint(
            "document_number = upper(document_number)", name=op.f("ck_customers_document_uppercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint(
            "document_type",
            "document_number",
            name=op.f("uq_customers_document_type_document_number"),
        ),
    )
    op.create_index(
        "ix_customers_name_trgm",
        "customers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_customers_is_default",
        "customers",
        ["is_default"],
        unique=True,
        postgresql_where="is_default",
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO customers (document_type, document_number, name, is_default) "
            "VALUES (:document_type, :document_number, :name, true)"
        ),
        DEFAULT_CUSTOMER,
    )
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    bind.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r, permissions p "
            "WHERE r.code = ANY(:role_codes) AND p.code = ANY(:codes)"
        ),
        {"role_codes": ROLES, "codes": [code for code, _ in PERMISSIONS]},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_customers_is_default", table_name="customers", postgresql_where="is_default")
    op.drop_index(
        "ix_customers_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("customers")
    # ### end Alembic commands ###
