"""create audit logs

Revision ID: 525470f17f53
Revises: ac51be84502f
Create Date: 2026-09-30 12:31:34.418801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [("audit.read", "Consultar la auditoría del sistema.")]
ROLES = ["admin"]
ACTIONS = [
    "product.create",
    "product.update",
    "product.stock_adjustment",
    "supplier.create",
    "supplier.update",
    "supplier.product_add",
    "supplier.product_update",
    "supplier.product_remove",
    "purchase.create",
    "purchase.discard",
    "purchase.confirm",
    "purchase.cancel",
    "sale.cancel",
    "cash_session.open",
    "cash_session.income",
    "cash_session.withdrawal",
    "cash_session.close",
    "user.create",
    "user.update",
    "user.password_reset",
]

# The audit log is append-only. Only a transaction that sets `app.audit_maintenance` (tests
# purging their committed rows, or a deliberate maintenance task) may update or delete it.
# This guards against changes from the application, not from a database owner.
IMMUTABLE_FUNCTION = """
CREATE FUNCTION audit_logs_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('app.audit_maintenance', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'audit_logs is append-only: % is not allowed', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$
"""

# revision identifiers, used by Alembic.
revision: str = "525470f17f53"
down_revision: str | Sequence[str] | None = "ac51be84502f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_label", sa.String(length=200), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "action IN (" + ", ".join(f"'{action}'" for action in ACTIONS) + ")",
            name=op.f("ck_audit_logs_action_valid"),
        ),
        sa.CheckConstraint(
            "entity_type IN ('product', 'supplier', 'purchase', 'sale', 'cash_session', 'user')",
            name=op.f("ck_audit_logs_entity_type_valid"),
        ),
        sa.CheckConstraint(
            "split_part(action, '.', 1) = entity_type",
            name=op.f("ck_audit_logs_action_matches_entity_type"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created_at", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity_label_trgm",
        "audit_logs",
        ["entity_label"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"entity_label": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_audit_logs_entity_type_entity_id_created_at",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_user_id_created_at", "audit_logs", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(sa.text(IMMUTABLE_FUNCTION))
    bind.execute(
        sa.text(
            "CREATE TRIGGER audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs "
            "FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable()"
        )
    )
    bind.execute(
        sa.text(
            "CREATE TRIGGER audit_logs_no_truncate BEFORE TRUNCATE ON audit_logs "
            "FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_immutable()"
        )
    )
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    bind.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r, permissions p "
            "WHERE r.code = ANY(:role_codes) AND p.code = ANY(:codes)"
        ),
        {"role_codes": ROLES, "codes": [code for code, _ in PERMISSIONS]},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_user_id_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity_type_entity_id_created_at", table_name="audit_logs")
    op.drop_index(
        "ix_audit_logs_entity_label_trgm",
        table_name="audit_logs",
        postgresql_using="gin",
        postgresql_ops={"entity_label": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")  # its triggers go with it
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION audit_logs_immutable()")
