"""create catalog tables

Revision ID: 2648e8a63496
Revises: ec5b97f3fd45
Create Date: 2026-09-28 13:19:48.762546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    ("products.read", "Consultar categorías y productos."),
    ("products.manage", "Crear y modificar categorías y productos."),
]
ROLE_PERMISSIONS = {
    "admin": ["products.read", "products.manage"],
    "inventory": ["products.read", "products.manage"],
    "cashier": ["products.read"],
}

# revision identifiers, used by Alembic.
revision: str = "2648e8a63496"
down_revision: str | Sequence[str] | None = "ec5b97f3fd45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trigram operator classes for the product search indexes.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        "uq_categories_name_lower", "categories", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), server_default="product", nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=20), nullable=False),
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("sale_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "average_cost",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "last_cost",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "current_stock",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "min_stock",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "reorder_point",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "target_stock",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type = 'product' OR (current_stock = 0 AND min_stock = 0 "
            "AND reorder_point = 0 AND target_stock = 0)",
            name=op.f("ck_products_service_without_stock"),
        ),
        sa.CheckConstraint("type IN ('product', 'service')", name=op.f("ck_products_type_valid")),
        sa.CheckConstraint(
            "unit_of_measure IN ('unit', 'pack', 'box', 'kg', 'g', 'l', 'ml', 'page')",
            name=op.f("ck_products_unit_of_measure_valid"),
        ),
        sa.CheckConstraint("average_cost >= 0", name=op.f("ck_products_average_cost_non_negative")),
        sa.CheckConstraint("last_cost >= 0", name=op.f("ck_products_last_cost_non_negative")),
        sa.CheckConstraint(
            "min_stock >= 0 AND min_stock <= reorder_point AND reorder_point <= target_stock",
            name=op.f("ck_products_stock_levels_order"),
        ),
        sa.CheckConstraint("sale_price >= 0", name=op.f("ck_products_sale_price_non_negative")),
        sa.CheckConstraint("sku = upper(sku)", name=op.f("ck_products_sku_uppercase")),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_products_tax_rate_range")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("barcode", name=op.f("uq_products_barcode")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(
        "ix_products_barcode_trgm",
        "products",
        ["barcode"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"barcode": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_products_sku_trgm",
        "products",
        ["sku"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sku": "gin_trgm_ops"},
    )
    op.create_table(
        "product_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("new_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "new_price >= 0", name=op.f("ck_product_price_history_new_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_product_price_history_changed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_price_history_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_price_history")),
    )
    op.create_index(
        op.f("ix_product_price_history_changed_by_id"),
        "product_price_history",
        ["changed_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_price_history_product_id_changed_at",
        "product_price_history",
        ["product_id", "changed_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    seed_permissions()


def seed_permissions() -> None:
    permissions = sa.table("permissions", sa.column("code"), sa.column("description"))
    op.bulk_insert(permissions, [{"code": c, "description": d} for c, d in PERMISSIONS])
    for role_code, permission_codes in ROLE_PERMISSIONS.items():
        op.get_bind().execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT r.id, p.id FROM roles r, permissions p "
                "WHERE r.code = :role_code AND p.code = ANY(:permission_codes)"
            ),
            {"role_code": role_code, "permission_codes": permission_codes},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_product_price_history_product_id_changed_at", table_name="product_price_history"
    )
    op.drop_index(
        op.f("ix_product_price_history_changed_by_id"), table_name="product_price_history"
    )
    op.drop_table("product_price_history")
    op.drop_index(
        "ix_products_sku_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"sku": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_products_name_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(
        "ix_products_barcode_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"barcode": "gin_trgm_ops"},
    )
    op.drop_table("products")
    op.drop_index("uq_categories_name_lower", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
    # pg_trgm is left installed: other objects may depend on it and it is harmless.
