"""create cash registers

Revision ID: 85b0113cde15
Revises: 16dc3234dce6
Create Date: 2026-09-29 14:42:10.622860

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
# (code, description, roles)
PERMISSIONS = [
    ("cash_registers.read", "Consultar cajas.", ["admin", "cashier"]),
    ("cash_registers.manage", "Crear, editar y desactivar cajas.", ["admin"]),
    (
        "cash.operate",
        "Abrir su propia caja y registrar ingresos y retiros en ella.",
        ["admin", "cashier"],
    ),
    ("cash.supervise", "Consultar las aperturas y movimientos de caja de todos.", ["admin"]),
]
DEFAULT_REGISTER = {"name": "Caja Principal", "description": "Caja creada en la instalación."}

# revision identifiers, used by Alembic.
revision: str = "85b0113cde15"
down_revision: str | Sequence[str] | None = "16dc3234dce6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_registers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_registers")),
    )
    op.create_index(
        "uq_cash_registers_name_lower",
        "cash_registers",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "cash_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cash_register_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("opening_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("opening_notes", sa.String(length=500), nullable=True),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_cash_sessions_status_valid")
        ),
        sa.CheckConstraint(
            "opening_amount >= 0", name=op.f("ck_cash_sessions_opening_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["cash_register_id"],
            ["cash_registers.id"],
            name=op.f("fk_cash_sessions_cash_register_id_cash_registers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cash_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_sessions")),
    )
    op.create_index(
        "ix_cash_sessions_cash_register_id_opened_at",
        "cash_sessions",
        ["cash_register_id", "opened_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_sessions_opened_at"), "cash_sessions", ["opened_at"], unique=False
    )
    op.create_index(
        "ix_cash_sessions_user_id_opened_at",
        "cash_sessions",
        ["user_id", "opened_at"],
        unique=False,
    )
    op.create_index(
        "uq_cash_sessions_open_register",
        "cash_sessions",
        ["cash_register_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "uq_cash_sessions_open_user",
        "cash_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "cash_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cash_session_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("concept", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(concept) <> ''", name=op.f("ck_cash_movements_concept_not_blank")
        ),
        sa.CheckConstraint(
            "movement_type IN ('income', 'withdrawal')",
            name=op.f("ck_cash_movements_movement_type_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_movements_amount_positive")),
        sa.ForeignKeyConstraint(
            ["cash_session_id"],
            ["cash_sessions.id"],
            name=op.f("fk_cash_movements_cash_session_id_cash_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cash_movements_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
    )
    op.create_index(
        "ix_cash_movements_cash_session_id_created_at",
        "cash_movements",
        ["cash_session_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_cash_movements_user_id"), "cash_movements", ["user_id"], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(
        sa.text("INSERT INTO cash_registers (name, description) VALUES (:name, :description)"),
        DEFAULT_REGISTER,
    )
    for code, description, roles in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
        bind.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT r.id, p.id FROM roles r, permissions p "
                "WHERE r.code = ANY(:role_codes) AND p.code = :code"
            ),
            {"role_codes": roles, "code": code},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _, _ in PERMISSIONS]},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cash_movements_user_id"), table_name="cash_movements")
    op.drop_index("ix_cash_movements_cash_session_id_created_at", table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(
        "uq_cash_sessions_open_user",
        table_name="cash_sessions",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(
        "uq_cash_sessions_open_register",
        table_name="cash_sessions",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_cash_sessions_user_id_opened_at", table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_opened_at"), table_name="cash_sessions")
    op.drop_index("ix_cash_sessions_cash_register_id_opened_at", table_name="cash_sessions")
    op.drop_table("cash_sessions")
    op.drop_index("uq_cash_registers_name_lower", table_name="cash_registers")
    op.drop_table("cash_registers")
    # ### end Alembic commands ###
