"""add closing to cash sessions

Revision ID: ac51be84502f
Revises: a201edd2370f
Create Date: 2026-09-30 11:13:26.533271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Closing is part of both permissions. Literals, so this migration never changes.
# (code, new description, previous description)
PERMISSION_DESCRIPTIONS = [
    (
        "cash.operate",
        "Abrir su propia caja, registrar ingresos y retiros en ella y cerrarla con el arqueo.",
        "Abrir su propia caja y registrar ingresos y retiros en ella.",
    ),
    (
        "cash.supervise",
        "Consultar las aperturas y movimientos de caja de todos y cerrar aperturas ajenas.",
        "Consultar las aperturas y movimientos de caja de todos.",
    ),
]

permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description"))


def _set_descriptions(new: bool) -> None:
    for code, description, previous in PERMISSION_DESCRIPTIONS:
        op.execute(
            permissions.update()
            .where(permissions.c.code == code)
            .values(description=description if new else previous)
        )


# revision identifiers, used by Alembic.
revision: str = "ac51be84502f"
down_revision: str | Sequence[str] | None = "a201edd2370f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cash_sessions", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("cash_sessions", sa.Column("closed_by_id", sa.Integer(), nullable=True))
    op.add_column(
        "cash_sessions",
        sa.Column("expected_cash", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "cash_sessions", sa.Column("counted_cash", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "cash_sessions", sa.Column("difference", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column("cash_sessions", sa.Column("closing_notes", sa.String(length=500), nullable=True))
    op.create_foreign_key(
        op.f("fk_cash_sessions_closed_by_id_users"),
        "cash_sessions",
        "users",
        ["closed_by_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_cash_sessions_closing_recorded"),
        "cash_sessions",
        "(status = 'closed' AND closed_at IS NOT NULL AND closed_by_id IS NOT NULL "
        "AND expected_cash IS NOT NULL AND counted_cash IS NOT NULL AND difference IS NOT NULL) "
        "OR (status = 'open' AND closed_at IS NULL AND closed_by_id IS NULL "
        "AND expected_cash IS NULL AND counted_cash IS NULL AND difference IS NULL "
        "AND closing_notes IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_cash_sessions_counted_cash_non_negative"), "cash_sessions", "counted_cash >= 0"
    )
    op.create_check_constraint(
        op.f("ck_cash_sessions_difference_consistent"),
        "cash_sessions",
        "difference = counted_cash - expected_cash",
    )
    _set_descriptions(new=True)


def downgrade() -> None:
    """Downgrade schema."""
    _set_descriptions(new=False)
    for name in ("difference_consistent", "counted_cash_non_negative", "closing_recorded"):
        op.drop_constraint(op.f(f"ck_cash_sessions_{name}"), "cash_sessions", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cash_sessions_closed_by_id_users"), "cash_sessions", type_="foreignkey"
    )
    op.drop_column("cash_sessions", "closing_notes")
    op.drop_column("cash_sessions", "difference")
    op.drop_column("cash_sessions", "counted_cash")
    op.drop_column("cash_sessions", "expected_cash")
    op.drop_column("cash_sessions", "closed_by_id")
    op.drop_column("cash_sessions", "closed_at")
    # ### end Alembic commands ###
