"""create purchases

Revision ID: 3c7c8fec033a
Revises: 817ffbfd6d32
Create Date: 2026-09-29 08:42:15.572783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    ("purchases.read", "Consultar compras."),
    ("purchases.manage", "Crear, editar, descartar y confirmar compras."),
    ("purchases.cancel", "Anular compras confirmadas (revierte inventario y costos)."),
]
ROLE_PERMISSIONS = {
    "admin": ["purchases.read", "purchases.manage", "purchases.cancel"],
    "inventory": ["purchases.read", "purchases.manage"],
}

MOVEMENT_TYPES_BEFORE = (
    "movement_type IN ('purchase_entry', 'sale', 'adjustment_in', 'adjustment_out', "
    "'purchase_return', 'sale_return', 'sale_cancellation')"
)
MOVEMENT_TYPES_AFTER = (
    "movement_type IN ('purchase_entry', 'sale', 'adjustment_in', 'adjustment_out', "
    "'purchase_return', 'purchase_cancellation', 'sale_return', 'sale_cancellation')"
)

# revision identifiers, used by Alembic.
revision: str = "3c7c8fec033a"
down_revision: str | Sequence[str] | None = "817ffbfd6d32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_sequences",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("prefix", sa.String(length=10), nullable=False),
        sa.Column("last_value", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "last_value >= 0", name=op.f("ck_document_sequences_last_value_non_negative")
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_document_sequences")),
    )
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("supplier_invoice_number", sa.String(length=50), nullable=True),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "discount_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "total", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "balance_due",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("confirmed_by_id", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'draft') = (number IS NULL)", name=op.f("ck_purchases_number_after_draft")
        ),
        sa.CheckConstraint(
            "status <> 'cancelled' OR (cancelled_at IS NOT NULL AND cancelled_by_id IS NOT NULL "
            "AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')",
            name=op.f("ck_purchases_cancellation_recorded"),
        ),
        sa.CheckConstraint(
            "status = 'draft' OR (confirmed_at IS NOT NULL AND confirmed_by_id IS NOT NULL)",
            name=op.f("ck_purchases_confirmation_recorded"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'cancelled')", name=op.f("ck_purchases_status_valid")
        ),
        sa.CheckConstraint(
            "amount_paid >= 0 AND amount_paid <= total", name=op.f("ck_purchases_amount_paid_range")
        ),
        sa.CheckConstraint(
            "balance_due = total - amount_paid", name=op.f("ck_purchases_balance_due_consistent")
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND discount_total >= 0 AND discount_total <= subtotal "
            "AND tax_total >= 0",
            name=op.f("ck_purchases_amounts_non_negative"),
        ),
        sa.CheckConstraint(
            "total = subtotal - discount_total + tax_total",
            name=op.f("ck_purchases_total_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_purchases_cancelled_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_id"],
            ["users.id"],
            name=op.f("fk_purchases_confirmed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_purchases_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchases_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint("number", name=op.f("uq_purchases_number")),
    )
    op.create_index(op.f("ix_purchases_confirmed_at"), "purchases", ["confirmed_at"], unique=False)
    op.create_index(op.f("ix_purchases_status"), "purchases", ["status"], unique=False)
    op.create_index(op.f("ix_purchases_supplier_id"), "purchases", ["supplier_id"], unique=False)
    op.create_index(
        "uq_purchases_supplier_invoice",
        "purchases",
        ["supplier_id", sa.literal_column("upper(supplier_invoice_number)")],
        unique=True,
        postgresql_where=sa.text("status != 'cancelled'"),
    )
    op.create_table(
        "purchase_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "discount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.CheckConstraint("discount >= 0", name=op.f("ck_purchase_items_discount_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_items_quantity_positive")),
        sa.CheckConstraint(
            "subtotal = round(quantity * unit_cost, 2) - discount AND subtotal >= 0",
            name=op.f("ck_purchase_items_subtotal_consistent"),
        ),
        sa.CheckConstraint(
            "tax_amount >= 0", name=op.f("ck_purchase_items_tax_amount_non_negative")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_purchase_items_tax_rate_range")
        ),
        sa.CheckConstraint(
            "total = subtotal + tax_amount", name=op.f("ck_purchase_items_total_consistent")
        ),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_purchase_items_unit_cost_non_negative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_purchase_items_purchase_id_purchases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_items")),
        sa.UniqueConstraint(
            "purchase_id", "product_id", name=op.f("uq_purchase_items_purchase_id_product_id")
        ),
    )
    op.create_index(
        op.f("ix_purchase_items_product_id"), "purchase_items", ["product_id"], unique=False
    )
    op.add_column("inventory_movements", sa.Column("purchase_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_inventory_movements_purchase_id"),
        "inventory_movements",
        ["purchase_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_purchase_id_purchases"),
        "inventory_movements",
        "purchases",
        ["purchase_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    # Autogenerate does not detect CHECK changes: new movement type and its purchase link.
    op.drop_constraint(
        op.f("ck_inventory_movements_movement_type_valid"), "inventory_movements", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_inventory_movements_movement_type_valid"),
        "inventory_movements",
        MOVEMENT_TYPES_AFTER,
    )
    op.create_check_constraint(
        op.f("ck_inventory_movements_purchase_movement_linked"),
        "inventory_movements",
        "NOT movement_type IN ('purchase_cancellation', 'purchase_entry') "
        "OR purchase_id IS NOT NULL",
    )

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO document_sequences (name, prefix, last_value) "
            "VALUES ('purchase', 'COMPRA', 0)"
        )
    )
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    for role_code, codes in ROLE_PERMISSIONS.items():
        bind.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT r.id, p.id FROM roles r, permissions p "
                "WHERE r.code = :role_code AND p.code = ANY(:codes)"
            ),
            {"role_code": role_code, "codes": codes},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )
    # Fails (and rolls back) if purchase movements exist: they reference the dropped tables.
    op.drop_constraint(
        op.f("ck_inventory_movements_purchase_movement_linked"),
        "inventory_movements",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_inventory_movements_movement_type_valid"), "inventory_movements", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_inventory_movements_movement_type_valid"),
        "inventory_movements",
        MOVEMENT_TYPES_BEFORE,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inventory_movements_purchase_id_purchases"),
        "inventory_movements",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_inventory_movements_purchase_id"), table_name="inventory_movements")
    op.drop_column("inventory_movements", "purchase_id")
    op.drop_index(op.f("ix_purchase_items_product_id"), table_name="purchase_items")
    op.drop_table("purchase_items")
    op.drop_index(
        "uq_purchases_supplier_invoice",
        table_name="purchases",
        postgresql_where=sa.text("status != 'cancelled'"),
    )
    op.drop_index(op.f("ix_purchases_supplier_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_status"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_confirmed_at"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_table("document_sequences")
    # ### end Alembic commands ###
