"""create inventory movements

Revision ID: 3737d7632657
Revises: 9c67e8deeca8
Create Date: 2026-09-28 15:27:59.988929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    ("inventory.read", "Consultar movimientos de inventario y reposición."),
    ("inventory.adjust", "Registrar ajustes manuales de inventario."),
]
ROLES = ["admin", "inventory"]

INBOUND = "movement_type IN ('adjustment_in', 'purchase_entry', 'sale_cancellation', 'sale_return')"

# revision identifiers, used by Alembic.
revision: str = "3737d7632657"
down_revision: str | Sequence[str] | None = "9c67e8deeca8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stock_before", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stock_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("average_cost_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"({INBOUND} AND stock_after = stock_before + quantity) "
            f"OR (NOT {INBOUND} AND stock_after = stock_before - quantity)",
            name=op.f("ck_inventory_movements_stock_after_consistent"),
        ),
        sa.CheckConstraint(
            "NOT movement_type IN ('adjustment_in', 'adjustment_out') "
            "OR (reason IS NOT NULL AND btrim(reason) <> '')",
            name=op.f("ck_inventory_movements_adjustment_reason_required"),
        ),
        sa.CheckConstraint(
            "movement_type IN ('purchase_entry', 'sale', 'adjustment_in', 'adjustment_out', "
            "'purchase_return', 'sale_return', 'sale_cancellation')",
            name=op.f("ck_inventory_movements_movement_type_valid"),
        ),
        sa.CheckConstraint(
            "average_cost_after >= 0",
            name=op.f("ck_inventory_movements_average_cost_after_non_negative"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_inventory_movements_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_inventory_movements_unit_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_movements_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_inventory_movements_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        op.f("ix_inventory_movements_created_at"),
        "inventory_movements",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_product_id_created_at",
        "inventory_movements",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_user_id"), "inventory_movements", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    bind.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r, permissions p "
            "WHERE r.code = ANY(:role_codes) AND p.code = ANY(:codes)"
        ),
        {"role_codes": ROLES, "codes": [code for code, _ in PERMISSIONS]},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows are removed by ON DELETE CASCADE.
    op.get_bind().execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_movements_user_id"), table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_product_id_created_at", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_movement_type"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_created_at"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    # ### end Alembic commands ###
