"""create sales

Revision ID: a201edd2370f
Revises: 85b0113cde15
Create Date: 2026-09-30 09:08:18.058567

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    ("sales.create", "Registrar ventas en su propia caja abierta."),
    ("sales.read", "Consultar sus propias ventas."),
    ("sales.read_all", "Consultar las ventas de todos los usuarios."),
    ("sales.cancel", "Anular ventas (revierte inventario y efectivo)."),
]
ROLE_PERMISSIONS = {
    "admin": ["sales.create", "sales.read", "sales.read_all", "sales.cancel"],
    "cashier": ["sales.create", "sales.read"],
}
# (code, name, is_cash, sort_order)
PAYMENT_METHODS = [
    ("cash", "Efectivo", True, 1),
    ("nequi", "Nequi", False, 2),
    ("daviplata", "Daviplata", False, 3),
    ("transfer", "Transferencia", False, 4),
    ("debit_card", "Tarjeta débito", False, 5),
    ("credit_card", "Tarjeta crédito", False, 6),
    ("other", "Otro", False, 7),
]
CASH_TYPES_BEFORE = "movement_type IN ('income', 'withdrawal')"
CASH_TYPES_AFTER = "movement_type IN ('income', 'withdrawal', 'sale', 'sale_cancellation')"

# revision identifiers, used by Alembic.
revision: str = "a201edd2370f"
down_revision: str | Sequence[str] | None = "85b0113cde15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_cash", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
        sa.UniqueConstraint("code", name=op.f("uq_payment_methods_code")),
        sa.UniqueConstraint("name", name=op.f("uq_payment_methods_name")),
    )
    op.create_index(
        "uq_payment_methods_is_cash",
        "payment_methods",
        ["is_cash"],
        unique=True,
        postgresql_where="is_cash",
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="completed", nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("cash_session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "lines_discount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sale_discount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "discount_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("cancelled_by_id", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'cancelled' OR (cancelled_at IS NOT NULL AND cancelled_by_id IS NOT NULL "
            "AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')",
            name=op.f("ck_sales_cancellation_recorded"),
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'cancelled')", name=op.f("ck_sales_status_valid")
        ),
        sa.CheckConstraint(
            "discount_total = lines_discount + sale_discount",
            name=op.f("ck_sales_discount_total_consistent"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND lines_discount >= 0 AND sale_discount >= 0 "
            "AND discount_total <= subtotal AND tax_total >= 0 AND tax_total <= total",
            name=op.f("ck_sales_amounts_valid"),
        ),
        sa.CheckConstraint(
            "total = subtotal - discount_total", name=op.f("ck_sales_total_consistent")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_sales_cancelled_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cash_session_id"],
            ["cash_sessions.id"],
            name=op.f("fk_sales_cash_session_id_cash_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sales_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("number", name=op.f("uq_sales_number")),
    )
    op.create_index(op.f("ix_sales_cash_session_id"), "sales", ["cash_session_id"], unique=False)
    op.create_index("ix_sales_created_at", "sales", ["created_at"], unique=False)
    op.create_index(op.f("ix_sales_customer_id"), "sales", ["customer_id"], unique=False)
    op.create_index(op.f("ix_sales_status"), "sales", ["status"], unique=False)
    op.create_index("ix_sales_user_id_created_at", "sales", ["user_id", "created_at"], unique=False)
    op.create_table(
        "sale_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "discount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sale_discount_share",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.CheckConstraint(
            "discount >= 0 AND sale_discount_share >= 0",
            name=op.f("ck_sale_items_discounts_non_negative"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_items_quantity_positive")),
        sa.CheckConstraint(
            "tax_amount >= 0 AND tax_amount <= total", name=op.f("ck_sale_items_tax_amount_range")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_sale_items_tax_rate_range")
        ),
        sa.CheckConstraint(
            "total = round(quantity * unit_price, 2) - discount - sale_discount_share "
            "AND total >= 0",
            name=op.f("ck_sale_items_total_consistent"),
        ),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_sale_items_unit_cost_non_negative")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sale_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_items_sale_id_sales"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_items")),
        sa.UniqueConstraint("sale_id", "product_id", name=op.f("uq_sale_items_sale_id_product_id")),
    )
    op.create_index(op.f("ix_sale_items_product_id"), "sale_items", ["product_id"], unique=False)
    op.create_table(
        "sale_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_tendered", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "change_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sale_payments_amount_positive")),
        sa.CheckConstraint(
            "amount_tendered IS NULL OR amount_tendered >= amount",
            name=op.f("ck_sale_payments_tendered_covers_amount"),
        ),
        sa.CheckConstraint(
            "change_amount = COALESCE(amount_tendered, amount) - amount",
            name=op.f("ck_sale_payments_change_amount_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_sale_payments_payment_method_id_payment_methods"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
            name=op.f("fk_sale_payments_sale_id_sales"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_payments")),
    )
    op.create_index(
        op.f("ix_sale_payments_payment_method_id"),
        "sale_payments",
        ["payment_method_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sale_payments_sale_id"), "sale_payments", ["sale_id"], unique=False)
    op.add_column("cash_movements", sa.Column("sale_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_cash_movements_sale_id"), "cash_movements", ["sale_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_cash_movements_sale_id_sales"),
        "cash_movements",
        "sales",
        ["sale_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("inventory_movements", sa.Column("sale_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_inventory_movements_sale_id"), "inventory_movements", ["sale_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_sale_id_sales"),
        "inventory_movements",
        "sales",
        ["sale_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    op.drop_constraint(
        op.f("ck_cash_movements_movement_type_valid"), "cash_movements", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_cash_movements_movement_type_valid"), "cash_movements", CASH_TYPES_AFTER
    )
    op.create_check_constraint(
        op.f("ck_cash_movements_sale_movement_linked"),
        "cash_movements",
        "(movement_type IN ('sale', 'sale_cancellation')) = (sale_id IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_inventory_movements_sale_movement_linked"),
        "inventory_movements",
        "NOT movement_type IN ('sale', 'sale_cancellation') OR sale_id IS NOT NULL",
    )

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO document_sequences (name, prefix, last_value) VALUES ('sale', 'VENTA', 0)"
        )
    )
    for code, name, is_cash, sort_order in PAYMENT_METHODS:
        bind.execute(
            sa.text(
                "INSERT INTO payment_methods (code, name, is_cash, sort_order) "
                "VALUES (:code, :name, :is_cash, :sort_order)"
            ),
            {"code": code, "name": name, "is_cash": is_cash, "sort_order": sort_order},
        )
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    for role_code, codes in ROLE_PERMISSIONS.items():
        bind.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT r.id, p.id FROM roles r, permissions p "
                "WHERE r.code = :role_code AND p.code = ANY(:codes)"
            ),
            {"role_code": role_code, "codes": codes},
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # role_permissions rows are removed by ON DELETE CASCADE.
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in PERMISSIONS]},
    )
    bind.execute(sa.text("DELETE FROM document_sequences WHERE name = 'sale'"))
    op.drop_constraint(
        op.f("ck_inventory_movements_sale_movement_linked"), "inventory_movements", type_="check"
    )
    op.drop_constraint(
        op.f("ck_cash_movements_sale_movement_linked"), "cash_movements", type_="check"
    )
    op.drop_constraint(
        op.f("ck_cash_movements_movement_type_valid"), "cash_movements", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_cash_movements_movement_type_valid"), "cash_movements", CASH_TYPES_BEFORE
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inventory_movements_sale_id_sales"), "inventory_movements", type_="foreignkey"
    )
    op.drop_index(op.f("ix_inventory_movements_sale_id"), table_name="inventory_movements")
    op.drop_column("inventory_movements", "sale_id")
    op.drop_constraint(
        op.f("fk_cash_movements_sale_id_sales"), "cash_movements", type_="foreignkey"
    )
    op.drop_index(op.f("ix_cash_movements_sale_id"), table_name="cash_movements")
    op.drop_column("cash_movements", "sale_id")
    op.drop_index(op.f("ix_sale_payments_sale_id"), table_name="sale_payments")
    op.drop_index(op.f("ix_sale_payments_payment_method_id"), table_name="sale_payments")
    op.drop_table("sale_payments")
    op.drop_index(op.f("ix_sale_items_product_id"), table_name="sale_items")
    op.drop_table("sale_items")
    op.drop_index("ix_sales_user_id_created_at", table_name="sales")
    op.drop_index(op.f("ix_sales_status"), table_name="sales")
    op.drop_index(op.f("ix_sales_customer_id"), table_name="sales")
    op.drop_index("ix_sales_created_at", table_name="sales")
    op.drop_index(op.f("ix_sales_cash_session_id"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(
        "uq_payment_methods_is_cash", table_name="payment_methods", postgresql_where="is_cash"
    )
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
