"""add payment methods management and request origin to audit logs

Revision ID: 0faa0637cce2
Revises: 525470f17f53
Create Date: 2026-09-30 17:36:42.199222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Seed data is written as literals so this migration never changes if the code evolves.
PERMISSIONS = [
    (
        "payment_methods.manage",
        "Crear, renombrar, ordenar, activar y desactivar métodos de pago.",
    )
]
ROLES = ["admin"]
PREVIOUS_ENTITIES = ["product", "supplier", "purchase", "sale", "cash_session", "user"]
PREVIOUS_ACTIONS = [
    "product.create",
    "product.update",
    "product.stock_adjustment",
    "supplier.create",
    "supplier.update",
    "supplier.product_add",
    "supplier.product_update",
    "supplier.product_remove",
    "purchase.create",
    "purchase.discard",
    "purchase.confirm",
    "purchase.cancel",
    "sale.cancel",
    "cash_session.open",
    "cash_session.income",
    "cash_session.withdrawal",
    "cash_session.close",
    "user.create",
    "user.update",
    "user.password_reset",
]
NEW_ENTITIES = ["payment_method"]
NEW_ACTIONS = ["payment_method.create", "payment_method.update"]

# revision identifiers, used by Alembic.
revision: str = "0faa0637cce2"
down_revision: str | Sequence[str] | None = "525470f17f53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _in_values(column: str, values: list[str]) -> str:
    return f"{column} IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def _replace_audit_checks(entities: list[str], actions: list[str]) -> None:
    op.drop_constraint(op.f("ck_audit_logs_entity_type_valid"), "audit_logs", type_="check")
    op.drop_constraint(op.f("ck_audit_logs_action_valid"), "audit_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_audit_logs_entity_type_valid"), "audit_logs", _in_values("entity_type", entities)
    )
    op.create_check_constraint(
        op.f("ck_audit_logs_action_valid"), "audit_logs", _in_values("action", actions)
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("ip_address", postgresql.INET(), nullable=True))
    op.add_column("audit_logs", sa.Column("user_agent", sa.String(length=255), nullable=True))
    op.drop_constraint(op.f("uq_payment_methods_name"), "payment_methods", type_="unique")
    op.create_index(
        "uq_payment_methods_name_lower",
        "payment_methods",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###

    # Adding columns and constraints is DDL: the append-only trigger (row UPDATE/DELETE and
    # TRUNCATE) does not fire.
    _replace_audit_checks(PREVIOUS_ENTITIES + NEW_ENTITIES, PREVIOUS_ACTIONS + NEW_ACTIONS)

    bind = op.get_bind()
    for code, description in PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (code, description) VALUES (:code, :description)"),
            {"code": code, "description": description},
        )
    bind.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r, permissions p "
            "WHERE r.code = ANY(:role_codes) AND p.code = ANY(:codes)"
        ),
        {"role_codes": ROLES, "codes": [code for code, _ in PERMISSIONS]},
    )


def downgrade() -> None:
    """Downgrade schema.

    Fails if payment methods were audited (the log is append-only) or if two methods have
    names that differ only in case: both are data the previous schema cannot hold."""
    bind = op.get_bind()
    codes = [code for code, _ in PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})
    _replace_audit_checks(PREVIOUS_ENTITIES, PREVIOUS_ACTIONS)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_payment_methods_name_lower", table_name="payment_methods")
    op.create_unique_constraint(
        op.f("uq_payment_methods_name"),
        "payment_methods",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("audit_logs", "user_agent")
    op.drop_column("audit_logs", "ip_address")
    # ### end Alembic commands ###
